export default {
  BUSINESS_GET_SESSIONS_START: 'BUSINESS_GET_SESSIONS_START',
  BUSINESS_GET_SESSIONS_SUCCESS: 'BUSINESS_GET_SESSIONS_SUCCESS',
  BUSINESS_GET_SESSIONS_FAIL: 'BUSINESS_GET_SESSIONS_FAIL',

  BUSINESS_GET_SESSIONS_BY_DEVICE_START: 'BUSINESS_GET_SESSIONS_BY_DEVICE_START',
  BUSINESS_GET_SESSIONS_BY_DEVICE_SUCCESS: 'BUSINESS_GET_SESSIONS_BY_DEVICE_SUCCESS',
  BUSINESS_GET_SESSIONS_BY_DEVICE_FAIL: 'BUSINESS_GET_SESSIONS_BY_DEVICE_FAIL',

  BUSINESS_GET_SESSIONS_BY_COUNTRY_START: 'BUSINESS_GET_SESSIONS_BY_COUNTRY_START',
  BUSINESS_GET_SESSIONS_BY_COUNTRY_SUCCESS: 'BUSINESS_GET_SESSIONS_BY_COUNTRY_SUCCESS',
  BUSINESS_GET_SESSIONS_BY_COUNTRY_FAIL: 'BUSINESS_GET_SESSIONS_BY_COUNTRY_FAIL',

  BUSINESS_GET_USER_STATS_START: 'BUSINESS_GET_USER_STATS_START',
  BUSINESS_GET_USER_STATS_SUCCESS: 'BUSINESS_GET_USER_STATS_SUCCESS',
  BUSINESS_GET_USER_STATS_FAIL: 'BUSINESS_GET_USER_STATS_FAIL',
  BUSINESS_GET_USER_PREVIOUS_STATS_SUCCESS: 'BUSINESS_GET_USER_PREVIOUS_STATS_SUCCESS',
  BUSINESS_GET_USER_PREVIOUS_STATS_FAIL: 'BUSINESS_GET_USER_PREVIOUS_STATS_FAIL',

  BUSINESS_GET_USERS_GRAPH_START: 'BUSINESS_GET_USERS_GRAPH_START',
  BUSINESS_GET_USERS_GRAPH_SUCCESS: 'BUSINESS_GET_USERS_GRAPH_SUCCESS',
  BUSINESS_GET_USERS_GRAPH_FAIL: 'BUSINESS_GET_USERS_GRAPH_FAIL',

  BUSINESS_GET_SESSION_DURATION_GRAPH_START: 'BUSINESS_GET_SESSION_DURATION_GRAPH_START',
  BUSINESS_GET_SESSION_DURATION_GRAPH_SUCCESS: 'BUSINESS_GET_SESSION_DURATION_GRAPH_SUCCESS',
  BUSINESS_GET_SESSION_DURATION_GRAPH_FAIL: 'BUSINESS_GET_SESSION_DURATION_GRAPH_FAIL',

  BUSINESS_GET_SCREEN_SUPPORT_START: 'BUSINESS_GET_SCREEN_SUPPORT_START',
  BUSINESS_GET_SCREEN_SUPPORT_SUCCESS: 'BUSINESS_GET_SCREEN_SUPPORT_SUCCESS',
  BUSINESS_GET_SCREEN_SUPPORT_FAIL: 'BUSINESS_GET_SCREEN_SUPPORT_FAIL',

  BUSINESS_ON_CHANGE_REQUESTED_TIME: 'BUSINESS_ON_CHANGE_REQUESTED_TIME',
  BUSINESS_ON_CHANGE_GRAPH_MODE: 'BUSINESS_ON_CHANGE_GRAPH_MODE',
};
