import createTypes from '@/services/helpers/createTypes';

export default createTypes(`
  SET_IMAGE
  REMOVE_OFFER_IMAGE

  ON_CHANGE_DESCRIPTION

  ON_DATE_CHANGE
  ON_TOGGLE_DATE_VISIBILITY
  
  SET_DEFAULT_PLACE
  REMOVE_PLACE
  ADD_PLACE
  ERASE_ADDRESS
  EDIT_ADDRESS
  SET_PLACE

  GET_CATEGORIES_START
  GET_CATEGORIES_SUCCESS
  GET_CATEGORIES_FAIL
  SET_CATEGORY

  POST_OFFER_START
  POST_OFFER_SUCCESS
  POST_OFFER_FAIL
  
  UPLOAD_OFFER_IMAGE_START
  UPLOAD_OFFER_IMAGE_SUCCESS
  UPLOAD_OFFER_IMAGE_FAIL

  RESET_OFFER

  SET_OFFER_TO_EDIT
  
  UPDATE_OFFER_START
  UPDATE_OFFER_SUCCESS
  UPDATE_OFFER_FAIL
`);
