export default {
  GET_OFFERS_START: 'GET_OFFERS_START',
  GET_OFFERS_SUCCESS: 'GET_OFFERS_SUCCESS',
  GET_OFFERS_FAIL: 'GET_OFFERS_FAIL',

  GET_OFFER_BY_ID_START: 'GET_OFFER_BY_ID_START',
  GET_OFFER_BY_ID_SUCCESS: 'GET_OFFER_BY_ID_SUCCESS',
  GET_OFFER_BY_ID_FAIL: 'GET_OFFER_BY_ID_FAIL',

  GET_CATEGORIES_START: 'GET_CATEGORIES_START',
  GET_CATEGORIES_SUCCESS: 'GET_CATEGORIES_SUCCESS',
  GET_CATEGORIES_FAIL: 'GET_CATEGORIES_FAIL',

  ON_CHANGE_OFFER_FORM_FIELD: 'ON_CHANGE_OFFER_FORM_FIELD',
  ON_CHANGE_CATEGORY: 'ON_CHANGE_CATEGORY',

  FILTER_OFFERS_BY_CATEGORY: 'FILTER_OFFERS_BY_CATEGORY',
  FILTER_OFFERS_BY_COUNTRY: 'FILTER_OFFERS_BY_COUNTRY',
  FILTER_OFFERS_BY_SEARCH: 'FILTER_OFFERS_BY_SEARCH',
  TURN_OFF_OFFERS_FILTER: 'TURN_OFF_OFFERS_FILTER',

  DELETE_OFFER_START: 'DELETE_OFFER_START',
  DELETE_OFFER_SUCCESS: 'DELETE_OFFER_SUCCESS',
  DELETE_OFFER_FAIL: 'DELETE_OFFER_FAIL',

  RESET_OFFER_TO_UPDATE: 'RESET_OFFER_TO_UPDATE',

  UPDATE_OFFER_START: 'UPDATE_OFFER_START',
  UPDATE_OFFER_SUCCESS: 'UPDATE_OFFER_SUCCESS',
  UPDATE_OFFER_FAIL: 'UPDATE_OFFER_FAIL',
};
