import createTypes from '@/services/helpers/createTypes';

export default createTypes(`
  GET_FAVORITE_OFFERS_START
  GET_FAVORITE_OFFERS_SUCCESS
  GET_FAVORITE_OFFERS_FAIL

  POST_FAVORITE_OFFER_START
  POST_FAVORITE_OFFER_SUCCESS
  POST_FAVORITE_OFFER_FAIL

  DELETE_FAVORITE_OFFER_START
  DELETE_FAVORITE_OFFER_SUCCESS
  DELETE_FAVORITE_OFFER_FAIL

  NOTIFY_ABOUT_EXPIRING_OFFER
`);
