import createTypes from '@/services/helpers/createTypes';

export default createTypes(`
  SET_ADDRESS
  EDIT_ADDRESS
  ERASE_ADDRESS

  CHANGE_CALLING_CODE

  SET_LOGO
  REMOVE_LOGO

  CREATE_BUSINESS_START
  CREATE_BUSINESS_SUCCESS
  CREATE_BUSINESS_FAIL
  
  UPLOAD_IMAGE_START
  UPLOAD_IMAGE_SUCCESS
  UPLOAD_IMAGE_FAIL

  GET_BUSINESS_START
  GET_BUSINESS_SUCCESS
  GET_BUSINESS_FAIL

  RESET_BUSINESS
`);
