export default {
  GET_USERS_START: 'GET_USERS_START',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
  GET_USERS_FAIL: 'GET_USERS_FAIL',

  FILTER_USERS_BY_CATEGORY: 'FILTER_USERS_BY_CATEGORY',
  FILTER_USERS_BY_COUNTRY: 'FILTER_USERS_BY_COUNTRY',
  FILTER_USERS_BY_SEARCH: 'FILTER_USERS_BY_SEARCH',
  TURN_OFF_USERS_FILTER: 'TURN_OFF_USERS_FILTER',

  DELETE_USER_START: 'DELETE_USER_START',
  DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
  DELETE_USER_FAIL: 'DELETE_USER_FAIL',

  SET_USER_TO_UPDATE: 'SET_USER_TO_UPDATE',
  ON_CHANGE_USER_FORM_FIELD: 'ON_CHANGE_USER_FORM_FIELD',

  UPDATE_USER_START: 'UPDATE_USER_START',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_USER_FAIL: 'UPDATE_USER_FAIL',
};
