export default {
  GET_COMPANIES_START: 'GET_COMPANIES_START',
  GET_COMPANIES_SUCCESS: 'GET_COMPANIES_SUCCESS',
  GET_COMPANIES_FAIL: 'GET_COMPANIES_FAIL',

  FILTER_COMPANIES_BY_COUNTRY: 'FILTER_COMPANIES_BY_COUNTRY',
  FILTER_COMPANIES_BY_SEARCH: 'FILTER_COMPANIES_BY_SEARCH',
  TURN_OFF_COMPANIES_FILTER: 'TURN_OFF_COMPANIES_FILTER',

  DELETE_COMPANY_START: 'DELETE_COMPANY_START',
  DELETE_COMPANY_SUCCESS: 'DELETE_COMPANY_SUCCESS',
  DELETE_COMPANY_FAIL: 'DELETE_COMPANY_FAIL',

  ON_CHANGE_COMPANY_FORM_FIELD: 'ON_CHANGE_COMPANY_FORM_FIELD',
  SET_COMPANY_TO_UPDATE: 'SET_COMPANY_TO_UPDATE',
  UPDATE_COMPANY_START: 'UPDATE_COMPANY_START',
  UPDATE_COMPANY_SUCCESS: 'UPDATE_COMPANY_SUCCESS',
  UPDATE_COMPANY_FAIL: 'UPDATE_COMPANY_FAIL',
};
