import createTypes from '@/services/helpers/createTypes';

export default createTypes(`
  SET_INITIAL_USER_FOR_UPDATE

  UPDATE_USER_START
  UPDATE_USER_SUCCESS
  UPDATE_USER_FAIL

  UPDATE_EMAIL_START
  UPDATE_EMAIL_SUCCESS
  UPDATE_EMAIL_FAIL

  UPDATE_PASSWORD_START
  UPDATE_PASSWORD_SUCCESS
  UPDATE_PASSWORD_FAIL

  DELETE_USER_START
  DELETE_USER_SUCCESS
  DELETE_USER_FAIL

  UPDATE_NOTIFICATIONS_STATUS_START
  UPDATE_NOTIFICATIONS_STATUS_SUCCESS
  UPDATE_NOTIFICATIONS_STATUS_FAIL
`);
