import createTypes from '@/services/helpers/createTypes';

export default createTypes(`
  SET_TOKENS
  SET_NEW_ACCESS_TOKEN

  BOOTSTRAP_START
  BOOTSTRAP_SUCCESS
  BOOTSTRAP_REJECT
  BOOTSTRAP_FAIL

  GET_ACCESS_TOKEN_START
  GET_ACCESS_TOKEN_SUCCESS
  GET_ACCESS_TOKEN_FAIL

  GET_USER_START
  GET_USER_SUCCESS
  GET_USER_FAIL

  SIGN_UP_START
  SIGN_UP_SUCCESS
  SIGN_UP_FAIL

  SIGN_IN_START
  SIGN_IN_SUCCESS
  SIGN_IN_FAIL

  REMOVE_SESSION

  CHANGE_PASSWORD_SUCCESS

  SET_USER_AVATAR_CANCEL
  SET_USER_AVATAR_FAIL
  SET_USER_AVATAR_SUCCESS
`);
