export default {
  ON_CHANGE_LOGIN: 'ON_CHANGE_LOGIN',
  ON_TOGGLE_REMEMBER_SESSION: 'ON_TOGGLE_REMEMBER_SESSION',
  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOGOUT: 'LOGOUT',

  SET_TOKEN: 'SET_TOKEN',
  SET_ADMIN: 'SET_ADMIN',
};
