import createTypes from '@/services/helpers/createTypes';

export default createTypes(`
  GET_CATEGORIES_START
  GET_CATEGORIES_SUCCESS
  GET_CATEGORIES_FAIL

  SET_CATEGORY

  SEARCH_BY_USER_LOCATION_START
  SEARCH_BY_USER_LOCATION_SUCCESS
  SEARCH_BY_USER_LOCATION_FAIL

  GET_OFFER_START
  GET_OFFER_SUCCESS
  GET_OFFER_FAIL

  ON_CHANGE_SEARCH
  SET_SEARCH_LOCATION_SUCCESS
  EDIT_SEARCH_ADDRESS
  ERASE_SEARCH_LOCATION

  GET_OFFERS_START
  GET_OFFERS_SUCCESS
  GET_OFFERS_FAIL

  SET_CHOSEN_OFFER_LOCATION

  REFRESH_BY_LOCATION
  RESET_SEARCH_RESULTS
`);
