export default {
  SEND_NOTIFICATION_START: 'SEND_NOTIFICATION_START',
  SEND_NOTIFICATION_SUCCESS: 'SEND_NOTIFICATION_SUCCESS',
  SEND_NOTIFICATION_FAIL: 'SEND_NOTIFICATION_FAIL',

  SET_INITIAL_COUNTRIES: 'SET_INITIAL_COUNTRIES',
  SET_INITIAL_CATEGORIES: 'SET_INITIAL_CATEGORIES',

  ON_CHANGE_NOTIFICATION_TEXT: 'ON_CHANGE_NOTIFICATION_TEXT',
  ON_CHANGE_NOTIFICATION_COUNTRY: 'ON_CHANGE_NOTIFICATION_COUNTRY',
  ON_CHANGE_NOTIFICATION_CATEGORY: 'ON_CHANGE_NOTIFICATION_CATEGORY',
  ON_CHANGE_NOTIFICATION_DATE: 'ON_CHANGE_NOTIFICATION_DATE',
  ON_CHANGE_NOTIFICATION_TIME: 'ON_CHANGE_NOTIFICATION_TIME',

  GET_NOTIFICATIONS_START: 'GET_NOTIFICATIONS_START',
  GET_NOTIFICATIONS_SUCCESS: 'GET_NOTIFICATIONS_SUCCESS',
  GET_NOTIFICATIONS_FAIL: 'GET_NOTIFICATIONS_FAIL',

  GET_NOTIFICATION_BY_ID_START: 'GET_NOTIFICATION_BY_ID_START',
  GET_NOTIFICATION_BY_ID_SUCCESS: 'GET_NOTIFICATION_BY_ID_SUCCESS',
  GET_NOTIFICATION_BY_ID_FAIL: 'GET_NOTIFICATION_BY_ID_FAIL',

  UPDATE_NOTIfICATION_START: 'UPDATE_NOTIfICATION_START',
  UPDATE_NOTIfICATION_SUCCESS: 'UPDATE_NOTIfICATION_SUCCESS',
  UPDATE_NOTIfICATION_FAIL: 'UPDATE_NOTIfICATION_FAIL',

  DELETE_NOTIFICATION_START: 'DELETE_NOTIFICATION_START',
  DELETE_NOTIFICATION_SUCCESS: 'DELETE_NOTIFICATION_SUCCESS',
  DELETE_NOTIFICATION_FAIL: 'DELETE_NOTIFICATION_FAIL',
};
