import createTypes from '@/services/helpers/createTypes';

export default createTypes(`
  SET_INITIAL_BUSINESS_FOR_UPDATE

  UPDATE_USER_START
  UPDATE_USER_SUCCESS
  UPDATE_USER_FAIL

  UPDATE_NAME_START
  UPDATE_NAME_SUCCESS
  UPDATE_NAME_FAIL

  UPDATE_EMAIL_START
  UPDATE_EMAIL_SUCCESS
  UPDATE_EMAIL_FAIL
  COMPARED
  UPDATE_PASSWORD_START
  UPDATE_PASSWORD_SUCCESS
  UPDATE_PASSWORD_FAIL

  CHANGE_MOBILE_CODE
  REMOVE_PHONE_FIELD
  ADD_PHONE_FIELD
  ON_CHANGE_PHONE_VALUE

  UPDATE_CONTACTS_START
  UPDATE_CONTACTS_SUCCESS
  UPDATE_CONTACTS_FAIL

  SET_NEW_ADDRESS
  EDIT_NEW_ADDRESS
  ERASE_ADDRESS

  UPDATE_ADDRESS_START
  UPDATE_ADDRESS_SUCCESS
  UPDATE_ADDRESS_FAIL

  SET_NEW_LOGO
  REMOVE_NEW_LOGO

  UPLOAD_NEW_LOGO_START
  UPLOAD_NEW_LOGO_SUCCESS
  UPDATE_LOGO_START
  UPDATE_LOGO_SUCCESS
  UPDATE_LOGO_FAIL
  UPLOAD_NEW_LOGO_FAIL

  REMOVE_CURRENT_LOGO_START
  REMOVE_CURRENT_LOGO_SUCCESS
  REMOVE_CURRENT_LOGO_FAIL

  DELETE_USER_START
  DELETE_USER_SUCCESS
  DELETE_USER_FAIL
`);
