export default {
  USER_GET_SESSIONS_START: 'USER_GET_SESSIONS_START',
  USER_GET_SESSIONS_SUCCESS: 'USER_GET_SESSIONS_SUCCESS',
  USER_GET_SESSIONS_FAIL: 'USER_GET_SESSIONS_FAIL',

  USER_GET_SESSIONS_BY_DEVICE_START: 'USER_GET_SESSIONS_BY_DEVICE_START',
  USER_GET_SESSIONS_BY_DEVICE_SUCCESS: 'USER_GET_SESSIONS_BY_DEVICE_SUCCESS',
  USER_GET_SESSIONS_BY_DEVICE_FAIL: 'USER_GET_SESSIONS_BY_DEVICE_FAIL',

  USER_GET_SESSIONS_BY_COUNTRY_START: 'USER_GET_SESSIONS_BY_COUNTRY_START',
  USER_GET_SESSIONS_BY_COUNTRY_SUCCESS: 'USER_GET_SESSIONS_BY_COUNTRY_SUCCESS',
  USER_GET_SESSIONS_BY_COUNTRY_FAIL: 'USER_GET_SESSIONS_BY_COUNTRY_FAIL',

  USER_GET_USER_STATS_START: 'USER_GET_USER_STATS_START',
  USER_GET_USER_STATS_SUCCESS: 'USER_GET_USER_STATS_SUCCESS',
  USER_GET_USER_STATS_FAIL: 'USER_GET_USER_STATS_FAIL',
  USER_GET_USER_PREVIOUS_STATS_SUCCESS: 'USER_GET_USER_PREVIOUS_STATS_SUCCESS',
  USER_GET_USER_PREVIOUS_STATS_FAIL: 'USER_GET_USER_PREVIOUS_STATS_FAIL',

  USER_GET_USERS_GRAPH_START: 'USER_GET_USERS_GRAPH_START',
  USER_GET_USERS_GRAPH_SUCCESS: 'USER_GET_USERS_GRAPH_SUCCESS',
  USER_GET_USERS_GRAPH_FAIL: 'USER_GET_USERS_GRAPH_FAIL',

  USER_GET_SESSION_DURATION_GRAPH_START: 'USER_GET_SESSION_DURATION_GRAPH_START',
  USER_GET_SESSION_DURATION_GRAPH_SUCCESS: 'USER_GET_SESSION_DURATION_GRAPH_SUCCESS',
  USER_GET_SESSION_DURATION_GRAPH_FAIL: 'USER_GET_SESSION_DURATION_GRAPH_FAIL',

  USER_GET_SCREEN_SUPPORT_START: 'USER_GET_SCREEN_SUPPORT_START',
  USER_GET_SCREEN_SUPPORT_SUCCESS: 'USER_GET_SCREEN_SUPPORT_SUCCESS',
  USER_GET_SCREEN_SUPPORT_FAIL: 'USER_GET_SCREEN_SUPPORT_FAIL',

  USER_ON_CHANGE_REQUESTED_TIME: 'USER_ON_CHANGE_REQUESTED_TIME',
  USER_ON_CHANGE_GRAPH_MODE: 'USER_ON_CHANGE_GRAPH_MODE',
};
